if (!window.lib) { window.lib = {}; }

var p; // shortcut to reference prototypes

// stage content:
(lib.summary = function() {
	this.initialize();

	// Layer 1
	this.summary = new lib.summary_1();
	this.summary.setTransform(512.7,384.2,1,1,0,0,0,512.7,384.2);

	this.addChild(this.summary);
}).prototype = p = new Container();
p.constructor = lib.summary;
p.nominalBounds = new Rectangle(0,0,1025.3,768.5);


// symbols:
(lib.mcTab2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("EApxgJ7QBkAAAABkIAAQvQAABkhkAAIiuAAMhQyAAAQhkAAAAhkIAAwvQAAhkBkAAMBQyAAAICuAA").cp();
	this.shape.setTransform(277.2,63.6);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 1
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(413.2,13);

	this.instance_1 = new lib.Bitmap9();
	this.instance_1.setTransform(154,13);

	this.instance_2 = new lib.Bitmap8();
	this.instance_2.setTransform(24.4,13);

	this.instance_3 = new lib.mass_4();
	this.instance_3.setTransform(335.2,62.8,1,1,0,0,0,51.7,49.8);

	this.instance_4 = new lib.answerBox_1();
	this.instance_4.setTransform(208.6,35,1,1,0,0,0,208.6,35);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.mcTab2;
p.nominalBounds = new Rectangle(0,0,554.5,127.2);

(lib.mcTab1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("EApxgJ7QBkAAAABkIAAQvQAABkhkAAIiuAAMhQyAAAQhkAAAAhkIAAwvQAAhkBkAAMBQyAAAICuAA").cp();
	this.shape.setTransform(277.2,63.6);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 1
	this.instance = new lib.Bitmap7();
	this.instance.setTransform(283.6,13);

	this.instance_1 = new lib.Bitmap6();
	this.instance_1.setTransform(154,13);

	this.instance_2 = new lib.Bitmap5();
	this.instance_2.setTransform(24.4,13);

	this.instance_3 = new lib.lock_butn1("single",0);
	this.instance_3.setTransform(509.8,33.1,1,1,0,0,0,20.3,16.8);

	this.instance_4 = new lib.gravity1();
	this.instance_4.setTransform(464.8,62.8,1,1,0,0,0,51.7,49.8);

	this.instance_5 = new lib.answerBox_1();
	this.instance_5.setTransform(208.6,35,1,1,0,0,0,208.6,35);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.mcTab1;
p.nominalBounds = new Rectangle(0,0,554.5,127.2);

(lib.mcTab0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 3
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("EApxgJ7QBkAAAABkIAAQvQAABkhkAAIiuAAMhQyAAAQhkAAAAhkIAAwvQAAhkBkAAMBQyAAAICuAA").cp();
	this.shape.setTransform(277.2,63.6);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 1
	this.instance = new lib.Bitmap4();
	this.instance.setTransform(413.2,13);

	this.instance_1 = new lib.Bitmap3();
	this.instance_1.setTransform(283.6,13);

	this.instance_2 = new lib.Bitmap2();
	this.instance_2.setTransform(154,13);

	this.instance_3 = new lib.Bitmap1();
	this.instance_3.setTransform(24.4,13);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(2));

	// Layer 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#e9e9e9").p("EApxgJ7IiuAAMhQyAAAQhkAAAABkIAAQvQAABkBkAAMBQyAAAICuAAQBkAAAAhkIAAwvQAAhkhkAA").f();
	this.shape_1.setTransform(277.2,63.6);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.shape_1}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.mcTab0;
p.nominalBounds = new Rectangle(0,0,554.5,127.2);

(lib.summary_1 = function() {
	this.initialize();

        
	// Layer 2
	this.mcCaption = new lib.closeCaptioning();
	this.mcCaption.setTransform(512.1,634,1,1,0,0,0,360,40);
    this.mcCaption.visible =false;
	   
	// Layer 3
	this.fadeScreen = new lib.mcStartScreen();
	this.fadeScreen.setTransform(512,408.5,1,1,0,0,0,512,245.5);
	
        
	// Layer 5
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AAAjUQgPABgMAHQgNAHgJALQgIAMgFAOQgFAOAAAOQAAAQAGAMQAGAMAKAHQALAHAQAAQANAAAJgFQAKgEAHgLIABABQgDANgFAMQgEALgJAIQgIAHgRABQgIAAgHgCQgGgBgFgFQgFgFgBgJIgVAAQAAAPAIAJQAHAJAMADQALAEAOAAQAUAAAOgIQAPgIAIgTQADgHADgJQACgKACgKIAXhuIgUAAIgEAYIAAAAIAAgBQgCgIgGgGQgHgGgIgDQgJgEgJAA").p("AgiirQAGgKAJgGQAJgFAKAAQAQAAAIAJQAJAJAAAPQAAAKgDALQgDALgGAJQgGAKgJAFQgIAGgMAAQgKAAgHgFQgHgFgEgHQgDgIAAgKQAAgJADgKQADgLAFgJ").p("AEIBSIgZBMIgBAAIgbhMIgRAAIAkBdIgGAQQgCAEgDACQgDACgFAAQgCAAgCgBQgDAAgBgBIAAAOQACABADAAQACABADAAQAHAAAEgDQAFgCAEgGQADgFAEgJIAohqIgQAA").p("ACpA2IgQAAIAAAcIgQAAIAAAOIAQAAIAAA7QAAAIACAFQADAEAFABQAEACAIAAIAMAAIAAgNIgHAAQgHAAgDgCQgCgCABgFIAAg5IASAAIAAgOIgSAAIAAgc").p("AB7AvIgPAAIAAASIAPAAIAAgS").p("ABNBSIgaBOIgahOIgRAAIAjBdIAQAAIAihdIgQAA").p("ABsBSIAABdIAPAAIAAhdIgPAA").p("AgYBjQADADABAGQgBAHgEACQgFACgHABQgHABgIACQgIABgHADQgIACgEAGQgFAGAAAKQAAAKAEAFQAFAGAHADQAGACAJAAQAKAAAIgEQAIgDAHgHQAAAIADADQAEADAGAAQADAAADAAQACgBACgBIAAgMQgCAAgBAAQAAAAgBAAQgEAAAAgCQgBgDABgFIAAgvQgBgLgFgGQgFgGgIgBQgIgCgIAAQgLAAgJADQgJADgFAHQgGAHAAALIAPAAQABgKAGgEQAGgEAKAAQAFAAAFACQAFABADAD").p("AhECWQABgFACgEQADgDAEgCQAEgCAFgBQAJgBAHgBQAIgBAEgDIAAAQQAAAEgDAFQgDAFgGADQgHADgKAAQgEAAgEAAQgEgCgDgDQgCgDgBgF").p("AhaBQQgNAAgIAFQgIAGgFALIgBAAIAAgUIgOAAIAABdIAPAAIAAgqQAAgRAIgKQAHgKATAAIAAgQ").p("AihBsIg5AAIAAAOIApAAQABALgFAKQgFAKgJAFQgKAFgNAAQgOAAgKgGQgKgIgFgLQgFgMAAgNQAAgLADgKQACgJAFgIQAGgIAIgEQAJgFALAAQAKAAAIADQAIADAFAGQAGAHABAJIARAAQgCgPgIgJQgHgKgMgEQgMgFgOAAQgPAAgMAGQgLAGgIAKQgHAJgEANQgEAMAAAOQAAANAEAMQAEALAIAJQAIAKALAFQAMAFAOAAQAIAAAHgCQAIgCAHgEQAGgEAFgHIAFAQIALAAIAAhD").f();
	this.shape.setTransform(522.9,200.1);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AhCg9IAOhEQACgJADgHQACgHAHgGQAGgHAJgFQAIgFAJAAQAHAAAFAFQAFAEAAAIQAAADgBAGQgBAGgCAIIgPBKIAVAAIAOhDQACgIACgIQADgHAFgGQAFgHAKgFQAJgGAIAAQAJAAAGAFQAFAFAAAIQAAADAAAEQgBAEgBADIgSBSIAWAAIAQhOQABgGABgHQACgHAAgGQAAgKgGgGQgFgHgIgDQgIgDgKAAQgMABgNAGQgLAGgHALQgEgNgIgFQgJgGgMAAQgNABgMAGQgLAGgJAKIAAAAIAFgUIgUAAIgbCCIAVAA").p("ACVBkQgIADgFAGQgGAGAAAJQAAAJAEAFQAFAFAHADQAHADAIABQAIACAGACQAHABAEAEQAFADAAAGQAAAFgEADQgDADgFABQgFACgFgBQgHABgGgCQgFgCgDgEQgEgEAAgHIgQAAQABAMAFAHQAFAHAKADQAIADALAAQAJAAAJgCQAJgEAGgGQAGgGAAgLQAAgJgEgGQgEgFgIgDQgHgCgIgCQgHgBgGgCQgHgCgFgDQgFgDAAgFQAAgFADgCQAEgDAEgBQAEgBAFAAQAFAAAFACQAFABADAEQADADABAGIAPAAQgBgMgFgGQgFgGgIgDQgJgCgKAAQgJAAgHAC").p("AAuBtQgGAGAAAJQAAAJAEAFQAFAFAHADQAHADAIABQAIACAGACQAHABAEAEQAFADAAAGQAAAFgEADQgDADgFABQgFACgFgBQgHABgGgCQgFgCgDgEQgEgEAAgHIgQAAQABAMAFAHQAFAHAKADQAIADALAAQAJAAAJgCQAJgEAGgGQAGgGAAgLQAAgJgEgGQgEgFgIgDQgHgCgIgCQgHgBgGgCQgHgCgFgDQgFgDAAgFQAAgFADgCQAEgDAEgBQAEgBAFAAQAFAAAFACQAFABADAEQADADABAGIAPAAQgBgMgFgGQgFgGgIgDQgJgCgKAAQgJAAgHACQgIADgFAG").p("AACBjQgHgBgIAAQgLAAgJACQgJADgFAHQgGAIAAALIAPAAQABgKAHgEQAFgEAKAAQAFAAAFACQAFAAACAEQADADABAGQgBAHgEABQgEADgHABQgHABgIABQgIACgHACQgIADgEAGQgFAFAAALQAAAJAEAGQAFAGAHADQAGACAKAAQAJAAAIgEQAIgDAGgHQAAAHADAEQAEADAGAAQAEAAACgBQADAAACgBIAAgMQgBAAgBAAQgCAAgBAAQgEAAAAgCQgBgDABgFIAAgwQgBgKgFgGQgFgGgIgC").p("AAFCRIAAAPQAAAFgDAFQgCAEgGAEQgHADgKAAQgEAAgEgBQgEgBgDgDQgCgDAAgFQAAgFACgEQADgEAEgBQAEgCAFgBQAJgBAHgBQAHgBAEgD").p("AhlBAIgpBtIgohtIgXAAIAACBIAPAAIAAhrIABAAIAoBrIAOAAIAphrIAABrIAQAAIAAiBIgXAA").f();
	this.shape_1.setTransform(391.3,198.3);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#000000").p("AgjkpIglCzIAVAAIAMg4IABAAQABADAGAEQAHADAIAAQAMAAAKgGQAMgGAIgLIABAAIgEAUIAVAAIAbiCIgVAAIgPBIQgCALgHAKQgHAJgJAGQgJAGgMAAQgJAAgHgEQgGgFAAgJQAAgCAAgEQABgEAAgEQABgEABgCIARhMIgWAA").p("AGsBXIAAgOIgHAAQgIAAgCgBQgDgCABgFIAAg6IATAAIAAgMIgTAAIAAgcIgQAAIAAAcIgPAAIAAAMIAPAAIAAA7QAAAJADAEQACAFAFABQAFACAIAAIAMAA").p("AFLAFQAIAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgDgHQgCgIgHgDQgIgEgLgBQgKAAgIAFQgIADgEAIIgBAAIAAgNIgOAAIAABcIAPAAIAAg1QAAgIADgHQADgGAGgEQAGgEAKAA").p("AD7gCQgJgFgNgBQgMABgKAFQgJAGgHALQgFALAAAOQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAALgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgHgEQgGgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgCgJgFgIQgFgIgHgE").p("ADlAFQAHAAAHAEQAFADADAGQAEAGABAHIg2AAQABgHADgGQADgGAGgDQAGgEAIAA").p("AE4DOQgIAEgFAIIAAAAIAAgOIgPAAIAABdIAQAAIAAg1QAAgIADgHQADgGAGgEQAGgEAKAAQAIAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgDgHQgCgIgHgEQgIgEgMgBQgKAAgHAF").p("ADdDJQgPABgKAGQgKAGgFALQgFALAAAOQAAAOAFALQAFALAKAGQAKAHAPAAQAPAAAKgHQAKgGAFgLQAFgLAAgOQAAgOgFgLQgFgLgKgGQgKgGgPgB").p("ADsDbQAHAEADAIQAEAIAAALQAAAMgEAHQgDAIgHAEQgHAEgIAAQgIAAgHgEQgGgEgEgIQgDgHgBgMQABgLADgIQAEgIAGgEQAHgEAIAAQAIAAAHAE").p("ACYgFIAABcIAPAAIAAhcIgPAA").p("ACYgpIAAATIAPAAIAAgTIgPAA").p("ABxgEQgJgEgLAAQgPABgJAGQgKAGgFALQgFALAAAOQAAAOAFALQAFALAKAGQAKAGAOAAQASAAAKgKQAKgJADgRIgQAAQgBAKgGAGQgHAGgLAAQgKAAgGgFQgGgEgDgIQgCgIAAgJQAAgJACgIQADgJAHgFQAFgFALAAQAKAAAGAFQAGAFACAJIAPAAQAAgMgGgHQgGgGgIgD").p("AAQgFIAABcIAPAAIAAhcIgPAA").p("AAQgpIAAATIAPAAIAAgTIgPAA").p("Ag8gqQgMAAgHAFQgGAGAAAMIAAAOIgQAAIAAAMIAQAAIAABQIAPAAIAAhQIASAAIAAgMIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACABQACAAACABIAAgOQgCgBgDAAQgCAAgDAA").p("AgwAHIAQAAIAABQIAPAAIAAhQIASAAIAAgMIgSAAIAAgNQAAgGAEgDQADgCAFAAQACAAACABQACAAACABIAAgOQgCgBgCAAQgCAAgDAAQgMAAgHAFQgHAGAAAMIAAAOIgQAAIAAAM").p("AisgCQgKAGgGALQgFALAAAOQAAAOAFALQAFALAKAHQAKAGAOAAQAQAAALgIQAKgIADgQIgPAAQgCAJgGAFQgHAEgJAAQgKAAgHgEQgGgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgCgJgFgIQgFgIgIgEQgIgFgNgBQgMABgKAF").p("AiJAJQAGADADAGQAEAGAAAHIg1AAQAAgHAEgGQADgGAGgDQAGgEAIAAQAHAAAGAE").p("AgjCoIgPAAIAAATIAPAAIAAgT").p("Ag/DaIAAgRQgMAAgIAGQgJAFgFALIAAAAIAAgTIgPAAIAABdIAQAAIAAgqQgBgSAIgJQAIgKASAA").p("AABDqQADgJAHgFQAGgFALAAQAKAAAFAFQAGAFACAJIAQAAQgBgMgFgHQgGgHgJgDQgIgEgLAAQgPABgJAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGANAAQASAAAKgKQALgJADgRIgQAAQgBAKgHAGQgGAGgMAAQgKAAgFgFQgHgEgCgIQgCgIAAgJQAAgJABgI").p("AgyDMIAABdIAPAAIAAhdIgPAA").p("AiACoIhUAAIAACBIARAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("ACOCoIAAATIAPAAIAAgTIgPAA").p("AB8DMIgSAAIAAgcIgPAAIAAAcIgRAAIAAANIARAAIAAA7QAAAJACAEQACAFAFABQAEACAJAAIALAAIAAgOIgGAAQgHAAgDgBQgCgCAAgFIAAg6IASAAIAAgN").p("ACODMIAABdIAPAAIAAhdIgPAA").p("AkUgBQgKAFgGALQgFALAAAOQAAAOAFALQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgLAAgOQAAgOgGgLQgFgLgKgFQgKgGgPgBQgOABgKAG").p("AjtAJQAHAEADAIQAEAIAAALQAAAMgEAHQgDAIgHAEQgGAEgJAAQgIAAgGgEQgHgEgEgIQgDgHgBgMQABgLADgIQAEgIAHgEQAGgEAIAAQAJAAAGAE").p("Ak4gCQgCgOgHgJQgIgJgLgFQgLgFgOAAQgTAAgOAJQgOAJgGAQQgIAOAAATQAAATAHAPQAHAPANAJQANAJAUAAQAYAAAPgOQAOgNADgZIgSAAQAAALgFAIQgEAJgIAEQgIAFgMAAQgPAAgKgHQgJgHgFgMQgEgNAAgOQAAgOAEgLQAFgMAJgHQAKgHAPAAQAJAAAIACQAHAEAFAGQAFAFACAKIARAA").p("AmWEkQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgLAAgOQAAgOgGgLQgFgLgKgGQgKgGgPgBQgOABgKAGQgKAGgGALQgFALAAAOQAAAOAFALQAGALAKAG").p("AmXDnQAEgIAHgEQAGgEAIAAQAJAAAGAEQAHAEADAIQAEAIAAALQAAAMgEAHQgDAIgHAEQgGAEgJAAQgIAAgGgEQgHgEgEgIQgDgHgBgMQABgLADgI").p("AkeCnQgNAAgGAGQgHAFAAAMIAAAOIgQAAIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACABQADAAACABIAAgOQgDAAgCgBQgDAAgCAA").f();
	this.shape_2.setTransform(262.6,209);

	this.shape_3 = new Shape();
	this.shape_3.graphics.f("#000000").p("AA6j1IhSAAIAMg5IBcAAIAEgUIh0AAIglCzIAXAAIAShSIBRAAIAFgU").p("ABajWQgCAEAAAFIgLAAIgBAJIAKAAIgMA1IAKAAIAMg1IAMAAIABgJIgLAAQAAgEABgDQACgEACgCQABgDAFAAQACAAABAAQABAAABABIACgIQgCgBgCgBQgCAAgCAAQgGAAgEADQgEABgBAEQgCAEgBAE").p("AEjAgIAABPIAPAAIAAhPIASAAIAAgOIgSAAIAAgNQAAgFADgCQAEgDAFAAQACAAACABQACAAADABIAAgOQgDAAgCAAQgDgBgCAAQgNAAgGAGQgHAFAAALIAAAOIgQAAIAAAOIAQAA").p("ADdAQQgOAAgKAHQgKAFgGALQgFAMAAANQAAAOAFALQAGALAKAHQAKAGAOAAQAPAAAKgGQAKgHAFgLQAGgLAAgOQAAgNgGgMQgFgLgKgFQgKgHgPAA").p("ADdAdQAIAAAHAEQAHAFADAIQAEAHAAALQAAAMgEAHQgDAJgHAEQgHADgIAAQgIAAgGgDQgHgEgEgJQgDgHgBgMQABgLADgHQAEgIAHgFQAGgEAIAA").p("ABjBSQgCAJgGAEQgHAEgKAAQgKAAgGgDQgGgFgEgHQgCgGAAgJIBGAAQAAgIgDgKQgBgJgFgIQgFgIgIgFQgIgFgNAAQgMAAgKAGQgKAGgGALQgGALAAAOQABAOAFALQAFAMAJAGQAKAGAPAAQAQAAALgIQAKgIADgPIgPAA").p("ABjA4Ig1AAQAAgIADgFQAEgGAFgEQAGgEAJAAQAHAAAGAEQAGAEADAGQADAFABAI").p("AgDATQgJgDgKAAQgPAAgKAHQgKAGgEALQgFAMAAAOQAAANAFAMQAFAKAJAGQAKAGAPAAQARAAAJgKQALgJADgRIgQAAQgBALgGAFQgHAGgKAAQgKAAgGgFQgGgEgDgIQgDgIAAgIQAAgKADgIQADgJAGgFQAGgFALAAQAJAAAGAFQAGAFABAJIAQAAQgBgLgFgIQgGgGgIgE").p("AhrAmIAAAAIAAgUIgPAAIAABdIAQAAIAAgqQgBgRAIgKQAIgKATAAIAAgQQgNAAgIAFQgJAGgFAL").p("AArDBIgPAAIAAASIAPAAIAAgS").p("AAcDkIAABdIAPAAIAAhdIgPAA").p("AALDkIgSAAIAAgcIgPAAIAAAcIgQAAIAAAOIAQAAIAAA7QAAAIACAEQADAFAFABQAEACAIAAIALAAIAAgNIgHAAQgGAAgDgCQgCgCAAgFIAAg5IASAAIAAgO").p("AA/ESQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgLQAFgLAAgOQAAgNgFgMQgFgLgKgFQgKgHgPAAQgPAAgKAHQgKAFgFALQgFAMAAAN").p("ABTEAQAEgIAGgFQAGgEAJAAQAIAAAHAEQAGAFAEAIQAEAHAAALQAAAMgEAHQgEAJgGAEQgHADgIAAQgJAAgGgDQgGgEgEgJQgEgHgBgMQABgLAEgH").p("AhWDiQgPAAgJAHQgKAGgEALQgFAMAAAOQAAANAFAMQAFAKAJAGQAKAGAOAAQARAAALgKQALgJACgRIgQAAQgBALgHAFQgGAGgLAAQgKAAgGgFQgGgEgDgIQgDgIAAgIQAAgKADgIQADgJAGgFQAGgFAMAAQAJAAAGAFQAGAFABAJIAQAAQgBgLgFgIQgFgGgKgEQgIgDgLAA").p("ADGDmQgHAEgFAJIAAAAIAAgPIgPAAIAABdIAQAAIAAg1QAAgIACgHQAEgGAFgEQAGgEAKAAQAJAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgDgHQgCgIgHgEQgIgEgMAAQgKAAgIAE").p("Ai4AQQgPAAgKAHQgKAFgFALQgFAMAAANQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgLQAFgLAAgOQAAgNgFgMQgFgLgKgFQgKgHgPAA").p("AipAhQAGAFAEAIQADAHAAALQAAAMgDAHQgEAJgGAEQgHADgIAAQgIAAgHgDQgHgEgDgJQgEgHgBgMQABgLAEgHQADgIAHgFQAHgEAIAAQAIAAAHAE").p("AjxgRIhVAAIAACAIARAAIAAg7IA8AAIAAgOIg8AAIAAgoIBEAAIAAgP").p("AlGFBIARAAIAAg7IA8AAIAAgOIg8AAIAAgpIBEAAIAAgOIhVAAIAACA").p("AiVDBIgPAAIAAASIAPAAIAAgS").p("AiwDiQgNAAgIAFQgIAGgFALIgBAAIAAgUIgOAAIAABdIAQAAIAAgqQgBgRAIgKQAIgKASAAIAAgQ").p("AikDkIAABdIAPAAIAAhdIgPAA").f();
	this.shape_3.setTransform(132.3,206.5);

	// Layer 4
	this.mcTab2 = new lib.mcTab2();
	this.mcTab2.setTransform(329.2,586,1,1,0,0,0,277.2,63.6);

	this.mcTab1 = new lib.mcTab1();
	this.mcTab1.setTransform(329.2,449.8,1,1,0,0,0,277.2,63.6);

	this.box2 = new lib.formulaBox_31();
	this.box2.setTransform(818.1,584.6,1,1,0,0,0,147.5,33.8);

	this.box1 = new lib.formulaBox_2();
	this.box1.setTransform(818.1,448.4,1,1,0,0,0,147.5,33.8);

	this.mcTab0 = new lib.mcTab0();
	this.mcTab0.setTransform(329.2,313.6,1,1,0,0,0,277.2,63.6);

	this.box0 = new lib.formulaBox_1();
	this.box0.setTransform(818.1,312.2,1,1,0,0,0,147.5,33.8);

	// Layer 2
	this.text = new Text("Summary", "20px HelveticaNeueLT Std", "#000000");
	this.text.textBaseline = "top";
	this.text.lineHeight = 20;
	this.text.setTransform(20,90);

	this.text_1 = new Text("Click each row to see how mass and the coefficient of friction affect the frictional force of a moving object.", "18px HelveticaNeueLT Std", "#6e6e6e");
	this.text_1.textBaseline = "top";
	this.text_1.lineHeight = 18;
	this.text_1.lineWidth = 957;
	this.text_1.setTransform(20,120);

	// Layer 1
	this.instance = new lib.OST1L_area2();
	this.instance.setTransform(512,84.4,1,1,0,0,0,512,84.4);

	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(512.7,290,1,1,0,0,0,512.7,290);

	this.addChild(this.instance_1,this.instance,this.text_1,this.text,this.box0,this.mcTab0,this.box1,this.box2,this.mcTab1,this.mcTab2,this.shape_3,this.shape_2,this.shape_1,this.shape,this.fadeScreen,this.mcCaption);
}).prototype = p = new Container();
p.constructor = lib.summary_1;
p.nominalBounds = new Rectangle(0,0,1025.3,768.5);

(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#e5e5e5").p("EBQHg8BMigNAAAMAAAB4EMCgNAAAMAAAh4E").f();
	this.shape.setTransform(512.7,384.2);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.Symbol1;
p.nominalBounds = new Rectangle(0,0,1025.3,768.5);

(lib.OST1L_area2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#ffffff").p("EBQAgMfMif/AAAIAAY/MCf/AAAIAA4/").f();
	this.shape.setTransform(512,80);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.OST1L_area2;
p.nominalBounds = new Rectangle(0,0,1024,160);

(lib.answerBox_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#e9e9e9").p("EAnDgJ7MhQyAAAQhkAAAABkIAAQvQAABkBkAAMBQyAAAICuAAQBkAAAAhkIAAwvQAAhkhkAAIiuAA").f();
	this.shape.setTransform(277.2,63.6);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.answerBox_1;
p.nominalBounds = new Rectangle(0,0,554.5,127.2);

(lib.forceOfFriction1 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AgWiIQgPABgKAGQgKAHgEALQgFAMAAAOQAAANAFAMQAFAKAJAGQAKAGAPAAQARAAAKgKQAKgJADgRIgQAAQgBAKgGAGQgHAGgKAAQgKAAgGgFQgGgEgDgIQgDgIAAgIQAAgKADgIQADgJAGgFQAGgFALAAQAJAAAHAFQAFAFABAJIAQAAQgBgLgFgIQgGgHgIgDQgJgEgKAA").p("AhIiIQgNAAgIAGQgIAGgFAKIgBAAIAAgTIgOAAIAABdIAPAAIAAgqQAAgRAIgKQAHgKATAAIAAgR").p("Ai4iIQgPABgKAGQgKAGgFALQgFAMAAANQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgLQAFgLAAgOQAAgNgFgMQgFgLgKgGQgKgGgPgB").p("AifhEQgEAJgGAEQgHADgIAAQgIAAgHgDQgHgEgDgJQgEgHAAgMQAAgLAEgHQADgJAHgEQAHgEAIAAQAIAAAHAEQAGAEAEAJQADAHAAALQAAAMgDAH").p("AijAoIAAATIAPAAIAAgTIgPAA").p("AgWAwIAAAcIgQAAIAAAOIAQAAIAAA6QAAAJACAFQADAEAFACQAEABAIAAIALAAIAAgOIgHAAQgGAAgCgBQgDgBAAgGIAAg5IASAAIAAgOIgSAAIAAgcIgPAA").p("AjxipIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjxAoIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjhBMIAABdIAQAAIAAgpQgBgSAIgKQAIgKASAAIAAgRQgMAAgIAGQgJAGgFAKIgBAAIAAgTIgOAA").p("AhFBcQAGAFABAJIARAAQgCgLgFgHQgFgIgKgDQgIgEgKAAQgPABgKAGQgKAHgEALQgFAMAAANQAAAPAFAKQAFALAJAGQAKAGAOAAQASAAAKgJQALgKACgRIgPAAQgCAKgGAHQgHAGgLAAQgKAAgGgFQgGgFgCgIQgDgHAAgKQAAgJACgIQADgIAHgFQAGgFALAAQAJAAAGAE").p("AijBMIAABdIAPAAIAAhdIgPAA").p("AE9iqQgNAAgGAGQgHAFAAAMIAAAOIgQAAIAAAOIAQAAIAABPIAPAAIAAhPIASAAIAAgOIgSAAIAAgNQAAgGADgCQAEgDAFAAQACAAACABQADAAACABIAAgOQgDAAgCAAQgDgBgCAA").p("ADdiIQgOABgKAGQgKAGgGALQgFAMAAANQAAAOAFALQAGALAKAHQAKAGAOAAQAPAAAKgGQAKgHAFgLQAGgLAAgOQAAgNgGgMQgFgLgKgGQgKgGgPgB").p("AD2hpQAEAHAAALQAAAMgEAHQgDAJgHAEQgGADgJAAQgIAAgGgDQgHgEgEgJQgDgHgBgMQABgLADgHQAEgJAHgEQAGgEAIAAQAJAAAGAEQAHAEADAJ").p("AByhkQgCgJgFgIQgFgIgIgFQgIgFgNgBQgMABgKAGQgKAGgGALQgFALAAAOQAAAOAFALQAFAMAKAGQAKAGAOAAQAQAAALgIQAKgIADgPIgPAAQgCAJgGAEQgHAEgJAAQgKAAgHgDQgGgFgDgHQgDgHAAgIIBGAAQAAgIgCgK").p("AAyhtQADgFAGgEQAGgEAIAAQAHAAAGAEQAGAEADAFQAEAGAAAIIg1AAQAAgIAEgG").p("AAdAoIAAATIAPAAIAAgTIgPAA").p("ACrBMIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgDAJAAQAJAAAFAFQAFAFAAAIIAAA/IAPAAIAAg9QAAgKgDgIQgCgHgHgFQgIgEgMgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAA").p("ACFBQQgKgGgPgBQgPABgKAGQgKAHgFALQgFAKAAAPQAAAOAFALQAFAKAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgKQAFgLAAgOQAAgPgFgKQgFgLgKgH").p("ACFBnQAEAIAAAMQAAALgEAIQgEAIgGADQgHAFgIAAQgIAAgHgFQgGgDgEgIQgEgIAAgLQAAgMAEgIQAEgIAGgDQAHgEAIAAQAIAAAHAEQAGADAEAI").p("AAdBMIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(39.6,68.5);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AA7hhIh1AAIgmCxIAYAAIARhRIBSAAIAEgUIhRAAIAMg4IBcAAIAFgU").p("ABTgTQgJAAgFAEQgGADgCAFQgCAFAAAIIAAAIIgMAAIAAAMIAMAAIAABJIAPAAIAAhJIARAAIAAgMIgRAAIAAgHQAAgHACgDQADgCAHAAQAEAAAEAAIACgMQgHgCgGAA").f();
	this.shape_1.setTransform(15.5,22.9);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#e80000").p("AGTmRIAAFLIgtAAIBLB3IBLh3IgrAAIAAlLIg+AA").f();
	this.shape_2.setTransform(56.7,45.5);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#ffaaa6","#e56b64"],[0,1],50.4,-48.2,50.4,48.3).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.forceOfFriction1;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.coef_2 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AGsiEIgTAAIAAgcIgPAAIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAEQACAFAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgN").p("AFNiHQgKAAgIAFQgIAEgEAIIgBAAIAAgOIgOAAIAABdIAPAAIAAg1QAAgIADgHQADgGAGgEQAGgEAKAAQAIAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgCgHQgDgIgHgEQgIgEgLgB").p("AFVBdQAFAFABAJIAAA/IAPAAIAAg+QAAgKgDgHQgDgIgHgEQgHgEgNgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAAIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgEAKAAQAJAAAEAF").p("AhliEIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACABQACAAADABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgQAA").p("AisiAQgKAGgFALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAPAAALgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgGgEQgHgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgMgBQgNABgKAG").p("AiJh1QAGADADAGQAEAGABAHIg2AAQAAgHAEgGQAEgGAFgDQAGgEAIAAQAHAAAGAE").p("AkUiAQgKAGgGALQgFALAAAOQAAAOAFALQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgLAAgOQAAgOgGgLQgFgLgKgGQgKgGgPgBQgOABgKAG").p("Ajth1QAHAEADAIQAFAIAAALQAAAMgFAHQgDAIgHAEQgGAEgJAAQgIAAgGgEQgHgEgEgIQgDgHgBgMQABgLADgIQAEgIAHgEQAGgEAIAAQAJAAAGAE").p("AkZA2QADAAACABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgPAAIAAANIAPAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACAB").p("AiAApIhUAAIAACBIARAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AlBiYQgIgJgLgFQgLgFgOAAQgTAAgOAJQgOAJgGAQQgIAPAAATQAAATAHAPQAHAPANAJQANAJAUAAQAYAAAPgOQAOgNADgZIgRAAQgBALgEAIQgFAJgIAEQgIAFgMAAQgPAAgKgHQgJgHgFgMQgEgNAAgOQAAgOAEgMQAFgMAJgHQAKgHAPAAQAJAAAIADQAHADAFAGQAFAGACAJIARAAQgCgOgHgJ").p("Al+BKQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgHQgKgGgPgB").p("AllBoQAFAIAAALQAAAMgFAIQgDAHgHAEQgGAEgJAAQgIAAgGgEQgGgEgFgHQgDgIgBgMQABgLADgIQAFgIAGgDQAGgFAIAAQAJAAAGAFQAHADADAI").p("AhwCqIAQAAIAAgqQgBgSAJgJQAHgKASAAIAAgRQgMAAgIAGQgJAFgFALIAAAAIAAgTIgPAAIAABd").p("ADliHQgMABgKAGQgJAGgGALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAQAAAKgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgHgEQgGgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgNgB").p("AEAhfIg2AAQABgHADgGQADgGAGgDQAGgEAIAAQAIAAAGAEQAFADAEAGQADAGABAH").p("ACYiEIAABdIAPAAIAAhdIgPAA").p("ACYioIAAATIAPAAIAAgTIgPAA").p("AB/h5QgGgHgIgDQgJgEgKAAQgPABgKAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGAOAAQASAAAKgKQALgJACgRIgPAAQgCAKgGAGQgHAGgLAAQgKAAgGgFQgGgEgCgIQgDgIAAgJQAAgJACgIQADgJAHgFQAGgFALAAQAJAAAGAFQAGAFACAJIAQAAQgBgMgGgH").p("ACOApIAAATIAPAAIAAgTIgPAA").p("AAfioIgPAAIAAATIAPAAIAAgT").p("AgGipQgMAAgHAGQgHAFAAAMIAAAOIgQAAIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGAEgDQADgCAGAAQABAAADABQABAAACABIAAgOQgCAAgCgBQgCAAgDAA").p("AgyApIAAATIAPAAIAAgTIgPAA").p("ABbAxIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAFQACAEAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgNIgTAAIAAgcIgPAA").p("AAQgnIAPAAIAAhdIgPAAIAABd").p("AAsBdQAGAFABAJIAQAAQgBgMgFgHQgGgHgJgDQgIgEgLAAQgPABgJAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGANAAQASAAALgJQAKgKADgRIgQAAQgBAKgHAHQgGAFgMAAQgKAAgFgFQgGgEgDgIQgCgIAAgJQAAgJABgIQAEgJAGgFQAGgFALAAQAKAAAGAF").p("AgyBNIAABdIAPAAIAAhdIgPAA").p("AD2BRQgKgGgPgBQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgH").p("AD2BoQAEAIAAALQAAAMgEAIQgDAHgHAEQgHAEgIAAQgIAAgGgEQgHgEgEgHQgDgIgBgMQABgLADgIQAEgIAHgDQAGgFAIAAQAIAAAHAFQAHADADAI").p("ACOBNIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(48.9,68.4);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AgihZIglCzIAVAAIAMg4IAAAAQACADAGADQAHADAIAAQAMAAALgGQALgFAJgLIAAAAIgEATIAVAAIAbiBIgVAAIgPBIQgCALgHAJQgHAJgJAGQgKAGgLABQgJAAgHgFQgGgEAAgJQAAgDAAgEQABgCAAgFQABgDABgCIAQhNIgVAA").f();
	this.shape_1.setTransform(11.3,26.9);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#e80000").p("AGdmRIAAFLIgtAAIBLB3IBLh3IgsAAIAAlLIg9AA").f();
	this.shape_2.setTransform(55.8,45.5);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#ffaaa6","#e56b64"],[0,1],50.4,-48.2,50.4,48.3).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.coef_2;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.mass_2 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AA7gcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAEAEQAEADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgGgCQgFgCgDgEQgEgEAAgHIgQAAQAAAMAGAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgIgDQgHgCgIgCQgHgCgGgBQgIgCgEgDQgFgCAAgFQAAgFADgCQAEgDAEgCQAEAAAFAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgJAAgHAD").p("AgOgfQgKAAgJADQgJADgFAHQgGAHAAALIAPAAQABgJAGgEQAGgEAKAAQAFAAAFABQAFABACADQADAEAAAGQAAAFgEACQgEADgHABQgHABgIABQgIACgHACQgIADgEAGQgFAFAAALQAAAJAEAGQAFAFAHADQAGACAJAAQAKAAAIgDQAIgDAGgHQAAAHADAEQAEACAGAAQAEAAACAAQADAAACgCIAAgLQgCAAAAAAQgCAAgBAAQgEAAAAgCQgBgDAAgFIAAgvQAAgLgFgGQgFgFgIgCQgHgCgJAA").p("AgfAZQAEgCAFgBQAIgBAIgBQAGgBAFgDIAAAPQAAAFgDAFQgCAEgGAEQgHADgKAAQgEAAgEgBQgEgBgDgDQgCgDgBgFQABgGACgDQADgEAEgB").p("AhlhAIgpBrIgohrIgYAAIAACAIAQAAIAAhqIABAAIAoBqIAOAAIAphqIAABqIAQAAIAAiAIgXAA").p("ACVgcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAFAEQADADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgFgCQgGgCgDgEQgEgEAAgHIgQAAQABAMAFAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgHgDQgIgCgHgCQgIgCgGgBQgIgCgEgDQgEgCgBgFQABgFACgCQAEgDAEgCQAFAAAEAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgIAAgIAD").f();
	this.shape.setTransform(27.6,58.1);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("ABBhBQgNAAgMAHQgMAGgIAKQgDgMgJgGQgIgFgMAAQgNAAgMAHQgLAFgJALIAAgBIAFgTIgUAAIgbCAIAVAAIAOhCQACgKADgHQACgGAHgHQAGgGAIgFQAJgFAJAAQAIAAAFAEQAFAFAAAIQAAACgBAHQgBAGgCAIIgQBIIAUAAIAPhCQACgIACgHQADgIAFgFQAFgHAKgFQAIgGAKAAQAIAAAGAFQAFAFAAAIQAAADAAADQgBAEgBADIgSBRIAVAAIARhMQABgGABgHQABgHAAgGQAAgLgFgGQgFgGgIgDQgIgDgJAA").f();
	this.shape_1.setTransform(15.4,24.3);

	// Layer 1
	this.shape_2 = new Shape();
	this.shape_2.graphics.lf(["#d3dade","#e8ecec","#f0f4f4"],[0,0.702,1],6,32.3,6,-30.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_2.setTransform(57.7,48.8);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.mass_2;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.gravity1 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AgLgmQgFgGgIgCQgIgCgIAAQgLAAgJADQgJADgFAHQgGAHAAAMIAPAAQABgKAGgEQAGgEAKAAQAFAAAFABQAFABADAEQADADABAGQgBAGgEACQgFADgHABQgGABgJABQgIACgHACQgIACgEAGQgFAGAAAKQAAAKAEAFQAFAGAHACQAGADAJAAQAKAAAIgEQAIgDAHgHQAAAIADADQAEADAGAAQADAAADgBQACAAACgCIAAgLQgCAAgBAAQAAAAgBAAQgDAAgBgCQgBgDABgFIAAgvQgBgLgFgF").p("AgVAAIAAAOQAAAFgDAFQgDAEgGAEQgHADgKAAQgEAAgEgBQgEgBgDgDQgCgDgBgFQABgGACgDQADgEAEgBQAFgCAFgBQAIgBAHgBQAIgBAEgC").p("AAIgtIAjBcIAQAAIAihcIgQAAIgaBMIgahMIgRAA").p("AiLgtIAABcIAPAAIAAgqQAAgRAIgJQAHgKATAAIAAgRQgNAAgHAGQgJAFgFALIgBAAIAAgTIgOAA").p("AijgpQgCgPgIgKQgHgJgMgEQgMgFgOAAQgPAAgMAGQgLAFgIAKQgHAKgEAMQgEANAAAOQAAANAEAKQAEAMAIAJQAIAJALAGQAMAFAOAAQAIAAAHgCQAIgCAHgEQAGgEAFgHIAFAQIALAAIAAhDIg5AAIAAAOIApAAQABALgFAKQgFAJgJAGQgKAFgNAAQgOAAgKgHQgKgHgFgMQgFgKAAgOQAAgKADgKQACgKAFgHQAGgIAIgFQAJgEALAAQAKAAAIADQAIADAFAGQAGAGABAKIARAA").p("AC7ggIAAgNIgSAAIAAgcIgQAAIAAAcIgQAAIAAANIAQAAIAAA6QAAAJACAEQADAFAFABQAEACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCABgFIAAg5IASAA").p("ADCgtIAkBbIgGARQgCADgDACQgDADgEAAQgDAAgCgBQgCAAgCgCIAAAPQACAAADABQACABADAAQAHAAAFgDQAFgCADgGQAEgGADgIIAphpIgQAAIgaBLIgBAAIgbhLIgRAA").p("AB7hRIgPAAIAAATIAPAAIAAgT").p("ABsgtIAABcIAPAAIAAhcIgPAA").f();
	this.shape.setTransform(34.3,59.7);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AgqhCQgIAMgFAOQgFAOAAAOQAAAPAFAMQAGAMALAHQALAHAPAAQAMAAALgFQAKgEAHgLIAAABQgCANgFAMQgEAMgJAHQgJAIgQAAQgIAAgHgCQgHgBgFgFQgEgFgCgIIgVAAQABAOAHAJQAIAJALAEQALAEAOAAQAUAAAPgJQAPgIAIgUQADgGACgJQADgKACgKIAXhuIgUAAIgEAZIAAAAIAAgBQgDgIgFgGQgHgGgIgDQgJgEgJAAQgPABgNAHQgMAHgJAL").p("AgbgzQAGgJAJgHQAIgFALAAQAQAAAIAJQAIAJAAAPQAAAKgCALQgDALgGAIQgGAKgJAFQgJAGgLAAQgKAAgHgEQgIgFgDgIQgDgHAAgKQAAgIACgLQADgLAGgJ").f();
	this.shape_1.setTransform(12.1,26.9);

	// Layer 1
	this.shape_2 = new Shape();
	this.shape_2.graphics.lf(["#d3dade","#e8ecec","#f0f4f4"],[0,0.702,1],6,32.3,6,-30.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_2.setTransform(57.7,48.8);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.gravity1;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.formulaBox_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("A2tlpMAtcAAAQBQAAAABQIAAIzQAABPhQAAMgtcAAAQhQAAAAhPIAAozQAAhQBQAA").cp();
	this.shape.setTransform(150.2,33.2);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 1
	this.instance = new lib.Bitmap13();
	this.instance.setTransform(-1.9,-1.9);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.formulaBox_1;
p.nominalBounds = new Rectangle(-1.9,-1.9,305,71);

(lib.F1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("ABBh1IiNAAIgsDVIAcAAIAVhhIBiAAIAFgYIhiAAIAOhEIBwAAIAFgY").p("ABcgSQgFADgDAGQgDAFgCAHQgCAHgCAIIgRAAIgDAOIARAAIgSBXIAQAAIAThXIATAAIADgOIgTAAQACgGABgHQABgFAEgDQADgEAIAAQACAAACAAQACABACAAIADgOQgEgBgDAAQgEgBgDAAQgKABgGAD").f();
	this.shape.setTransform(0.6,1.6);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.F1;
p.nominalBounds = new Rectangle(-11.4,-10.1,24.3,23.7);

(lib.mu1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AA9hqIgSBVQgDAOgIAKQgIALgLAIQgMAHgNAAQgLAAgIgFQgHgGgBgKQAAgEABgEQABgEAAgEQABgFABgDIAUhaIgaAAIgtDVIAaAAIAOhDIABAAQACAEAIAEQAHAEALAAQANAAANgIQAOgGAKgOIABAAIgFAYIAZAAIAgiaIgZAA").f();
	this.shape.setTransform(-1.4,6.4);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.mu1;
p.nominalBounds = new Rectangle(-10.1,-4.2,17.3,21.5);

(lib.m = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AAKhIQgKgHgOAAQgQABgOAHQgOAHgKANIgBgBIAGgXIgYAAIghCbIAaAAIARhRQACgLAEgIQADgJAIgHQAHgIAKgGQAKgGALAAQAKAAAGAFQAFAGAAAJQAAADgBAIQgBAHgCAKIgTBYIAYAAIAShQQABgJAEgKQADgJAGgHQAHgIAKgHQALgGALAAQAKAAAHAGQAGAGABAJQAAAEgBAEQgBAFgBAEIgVBiIAZAAIAUhdQABgHACgIQABgJAAgHQAAgMgGgIQgGgIgKgDQgKgEgLAAQgQABgOAHQgOAIgJAMQgEgPgKgG").f();
	this.shape.setTransform(-0.9,3.3);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.m;
p.nominalBounds = new Rectangle(-12.9,-4.6,24.1,15.9);

(lib.g = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AAHhuQgSAAgPAIQgPAJgKAOQgKANgGARQgFARAAASQAAARAGAPQAHAPANAHQANAJATAAQAOAAAMgFQANgGAIgNIABABQgEAQgGAOQgFAOgLAJQgJAKgUAAQgKAAgIgCQgJgCgFgGQgGgFgBgLIgZAAQAAARAJALQAJALAOAFQAOAEAPAAQAYABASgLQASgKAKgXQADgJADgKQADgLADgNIAciDIgYAAIgFAcIgBAAIAAgBQgCgJgHgHQgIgHgKgEQgKgEgMAA").p("AAPATQgLAIgNAAQgNAAgIgGQgJgGgEgKQgEgIAAgLQAAgLAEgNQADgMAHgMQAHgLAKgHQAKgHANAAQAUAAAKALQAKAKAAATQAAAMgEANQgDANgHAKQgHAMgLAG").f();
	this.shape.setTransform(-0.7,6.4);

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.g;
p.nominalBounds = new Rectangle(-9.3,-4.6,17.2,22.2);

(lib.summ_pannel1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#e5f4fd").p("ATulOMgjAAAAImqAAQhkAAAABkIAAHVQAABkBkAAIGgAAIAKAAIdiAAIFeAAICQAAQBkAAAAhkIAAnVQAAhkhkAAIiQAA").f().s("#ffffff").ss(4,1,1,3).p("ATulOICQAAQBkAAAABkIAAHVQAABkhkAAIiQAAIleAAI9iAAIgKAAImgAAQhkAAAAhkIAAnVQAAhkBkAAIGqAAMAjAAAA").cp();

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.summ_pannel1;
p.nominalBounds = new Rectangle(-150.4,-33.4,301.1,67);

(lib.lock_butn1 = function() {
	this.initialize();

	// Layer 5
	this.shape = new Shape();
	this.shape.graphics.lf(["#ffffff","#ffffff"],[0,1],-4.9,0,5,0).p("AAtghQAAgPgLgLQgLgLgQAAIgNAAQgQAAgKALQgLALAAAPIAAAPQgFAHAAALIAAArQAAAdAdAAIAoAAQAdAAAAgdIAAgrQAAgLgFgHIAAgP").p("AAbgbQgDgBgDAAIgoAAQgEAAgDABIAAgGQAAgJAGgFIAAgBQAGgFAIAAIANAAQAJAAAFAFQAGAGAAAJIAAAG").p("AAAASQAFAAAEADQADADAAAFQAAAFgDAEQgCABgBABIAAAPQAAADgBABQgCADgCAAIgBAAQgCAAgBgDQgCgBAAgDIAAgPQgCgBAAgBQgEgEAAgFQAAgFAEgDQADgDAEAA").f();
	this.shape.setTransform(18.4,19.5);

	// Layer 2
	this.shape_1 = new Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.498)").p("AgEhSQgLAHgLAKQgkAlAAAxQAAADAAACQACArAdAgQgTgbgBgjQAAgDAAgCQAAgyAkgkQAKgKAKgHIgJgN").p("AA/hXIgJgNQgcABgXANIAKANQAWgNAcgB").f();
	this.shape_1.setTransform(11.4,15.8);

	// Layer 1
	this.shape_2 = new Shape();
	this.shape_2.graphics.lf(["#4fade9","#008cee","#005df0"],[0,0.671,1],-15.1,0,15.2,0).p("ABrhrQgsgsg/AAQg9AAgtAsQgtAtAAA+QAAADAAADQACA7ArAqQAtAtA9AAQA/AAAsgtQArgqACg7QAAgDAAgDQAAg+gtgt").f();
	this.shape_2.setTransform(18.4,18.6);

	// Layer 3
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#282828","#000000"],[0,1],-16.7,0,16.8,0).p("AB3h2QgxgxhGAAQhEAAgxAxQgyAyAABEQAAAEAAADQADBBAvAvQAxAxBEAAQBGAAAxgxQAvgvAChBQAAgDAAgEQAAhEgxgy").f();
	this.shape_3.setTransform(18.4,18.6);

	// Layer 4
	this.shape_4 = new Shape();
	this.shape_4.graphics.lf(["rgba(0,199,255,0.6)","rgba(0,199,255,0.298)","rgba(0,199,255,0)"],[0,0.867,1],-18.3,0,18.4,0).p("ACDiCQg2g1hNAAQhLAAg2A1Qg2A3AABLQAAAEAAAEQADBHAzAzQA2A3BLAAQBNAAA2g3QAzgzADhHQAAgEAAgEQAAhLg2g3").f().s("rgba(255,255,255,0.6)").ss(1,1,1,3).p("ACDiCQA2A3AABLQAAAEAAAEQgDBHgzAzQg2A3hNAAQhLAAg2g3QgzgzgDhHQAAgEAAgEQAAhLA2g3QA2g1BLAAQBNAAA2A1").cp();
	this.shape_4.setTransform(18.4,18.4);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.lock_butn1;
p.nominalBounds = new Rectangle(0,0,36.9,36.9);

(lib.forceOfFriction2 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AgWiIQgPABgKAGQgKAHgEALQgFAMAAAOQAAANAFAMQAFAKAJAGQAKAGAPAAQARAAAKgKQAKgJADgRIgQAAQgBAKgGAGQgHAGgKAAQgKAAgGgFQgGgEgDgIQgDgIAAgIQAAgKADgIQADgJAGgFQAGgFALAAQAJAAAHAFQAFAFABAJIAQAAQgBgLgFgIQgGgHgIgDQgJgEgKAA").p("AhIiIQgNAAgIAGQgIAGgFAKIgBAAIAAgTIgOAAIAABdIAPAAIAAgqQAAgRAIgKQAHgKATAAIAAgR").p("Ai4iIQgPABgKAGQgKAGgFALQgFAMAAANQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgLQAFgLAAgOQAAgNgFgMQgFgLgKgGQgKgGgPgB").p("AifhEQgEAJgGAEQgHADgIAAQgIAAgHgDQgHgEgDgJQgEgHAAgMQAAgLAEgHQADgJAHgEQAHgEAIAAQAIAAAHAEQAGAEAEAJQADAHAAALQAAAMgDAH").p("AijAoIAAATIAPAAIAAgTIgPAA").p("AgWAwIAAAcIgQAAIAAAOIAQAAIAAA6QAAAJACAFQADAEAFACQAEABAIAAIALAAIAAgOIgHAAQgGAAgCgBQgDgBAAgGIAAg5IASAAIAAgOIgSAAIAAgcIgPAA").p("AjxipIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjxAoIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjhBMIAABdIAQAAIAAgpQgBgSAIgKQAIgKASAAIAAgRQgMAAgIAGQgJAGgFAKIgBAAIAAgTIgOAA").p("AhFBcQAGAFABAJIARAAQgCgLgFgHQgFgIgKgDQgIgEgKAAQgPABgKAGQgKAHgEALQgFAMAAANQAAAPAFAKQAFALAJAGQAKAGAOAAQASAAAKgJQALgKACgRIgPAAQgCAKgGAHQgHAGgLAAQgKAAgGgFQgGgFgCgIQgDgHAAgKQAAgJACgIQADgIAHgFQAGgFALAAQAJAAAGAE").p("AijBMIAABdIAPAAIAAhdIgPAA").p("AE9iqQgNAAgGAGQgHAFAAAMIAAAOIgQAAIAAAOIAQAAIAABPIAPAAIAAhPIASAAIAAgOIgSAAIAAgNQAAgGADgCQAEgDAFAAQACAAACABQADAAACABIAAgOQgDAAgCAAQgDgBgCAA").p("ADdiIQgOABgKAGQgKAGgGALQgFAMAAANQAAAOAFALQAGALAKAHQAKAGAOAAQAPAAAKgGQAKgHAFgLQAGgLAAgOQAAgNgGgMQgFgLgKgGQgKgGgPgB").p("AD2hpQAEAHAAALQAAAMgEAHQgDAJgHAEQgGADgJAAQgIAAgGgDQgHgEgEgJQgDgHgBgMQABgLADgHQAEgJAHgEQAGgEAIAAQAJAAAGAEQAHAEADAJ").p("AByhkQgCgJgFgIQgFgIgIgFQgIgFgNgBQgMABgKAGQgKAGgGALQgFALAAAOQAAAOAFALQAFAMAKAGQAKAGAOAAQAQAAALgIQAKgIADgPIgPAAQgCAJgGAEQgHAEgJAAQgKAAgHgDQgGgFgDgHQgDgHAAgIIBGAAQAAgIgCgK").p("AAyhtQADgFAGgEQAGgEAIAAQAHAAAGAEQAGAEADAFQAEAGAAAIIg1AAQAAgIAEgG").p("AAdAoIAAATIAPAAIAAgTIgPAA").p("ACrBMIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgDAJAAQAJAAAFAFQAFAFAAAIIAAA/IAPAAIAAg9QAAgKgDgIQgCgHgHgFQgIgEgMgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAA").p("ACFBQQgKgGgPgBQgPABgKAGQgKAHgFALQgFAKAAAPQAAAOAFALQAFAKAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgKQAFgLAAgOQAAgPgFgKQgFgLgKgH").p("ACFBnQAEAIAAAMQAAALgEAIQgEAIgGADQgHAFgIAAQgIAAgHgFQgGgDgEgIQgEgIAAgLQAAgMAEgIQAEgIAGgDQAHgEAIAAQAIAAAHAEQAGADAEAI").p("AAdBMIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(39.6,68.5);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AA+hYIh1AAIglCyIAYAAIARhSIBRAAIAFgUIhSAAIAMg4IBcAAIAFgU").p("ABDATQgBAEgBAFIgKAAIgCAJIALAAIgMA1IAKAAIAMg1IALAAIACgJIgMAAQABgEABgEQABgDACgDQACgCAFAAQACAAABAAQABAAABABIACgJQgCAAgCgBQgDAAgCAAQgGAAgEACQgDACgCAEQgBADgCAF").f();
	this.shape_1.setTransform(15.7,22);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#1494b8").p("AH3kgIhLh4IhLB4IAtAAIAAFKIA+AAIAAlKIArAA").f();
	this.shape_2.setTransform(56.7,44.7);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#b8d8f5","#71c4fc"],[0,1],-642,-47.5,-642.3,45.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.forceOfFriction2;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.coef_3 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AGsiEIgTAAIAAgcIgPAAIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAEQACAFAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgN").p("AFNiHQgKAAgIAFQgIAEgEAIIgBAAIAAgOIgOAAIAABdIAPAAIAAg1QAAgIADgHQADgGAGgEQAGgEAKAAQAIAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgCgHQgDgIgHgEQgIgEgLgB").p("AFVBdQAFAFABAJIAAA/IAPAAIAAg+QAAgKgDgHQgDgIgHgEQgHgEgNgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAAIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgEAKAAQAJAAAEAF").p("AhliEIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACABQACAAADABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgQAA").p("AisiAQgKAGgFALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAPAAALgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgGgEQgHgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgMgBQgNABgKAG").p("AiJh1QAGADADAGQAEAGABAHIg2AAQAAgHAEgGQAEgGAFgDQAGgEAIAAQAHAAAGAE").p("AkUiAQgKAGgGALQgFALAAAOQAAAOAFALQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgLAAgOQAAgOgGgLQgFgLgKgGQgKgGgPgBQgOABgKAG").p("Ajth1QAHAEADAIQAFAIAAALQAAAMgFAHQgDAIgHAEQgGAEgJAAQgIAAgGgEQgHgEgEgIQgDgHgBgMQABgLADgIQAEgIAHgEQAGgEAIAAQAJAAAGAE").p("AkZA2QADAAACABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgPAAIAAANIAPAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACAB").p("AiAApIhUAAIAACBIARAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AlBiYQgIgJgLgFQgLgFgOAAQgTAAgOAJQgOAJgGAQQgIAPAAATQAAATAHAPQAHAPANAJQANAJAUAAQAYAAAPgOQAOgNADgZIgRAAQgBALgEAIQgFAJgIAEQgIAFgMAAQgPAAgKgHQgJgHgFgMQgEgNAAgOQAAgOAEgMQAFgMAJgHQAKgHAPAAQAJAAAIADQAHADAFAGQAFAGACAJIARAAQgCgOgHgJ").p("Al+BKQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgHQgKgGgPgB").p("AllBoQAFAIAAALQAAAMgFAIQgDAHgHAEQgGAEgJAAQgIAAgGgEQgGgEgFgHQgDgIgBgMQABgLADgIQAFgIAGgDQAGgFAIAAQAJAAAGAFQAHADADAI").p("AhwCqIAQAAIAAgqQgBgSAJgJQAHgKASAAIAAgRQgMAAgIAGQgJAFgFALIAAAAIAAgTIgPAAIAABd").p("ADliHQgMABgKAGQgJAGgGALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAQAAAKgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgHgEQgGgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgNgB").p("ADzh1QAFADAEAGQADAGABAHIg2AAQABgHADgGQADgGAGgDQAGgEAIAAQAIAAAGAE").p("ACYiVIAPAAIAAgTIgPAAIAAAT").p("ACYiEIAABdIAPAAIAAhdIgPAA").p("AB/h5QgGgHgIgDQgJgEgKAAQgPABgKAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGAOAAQASAAAKgKQALgJACgRIgPAAQgCAKgGAGQgHAGgLAAQgKAAgGgFQgGgEgCgIQgDgIAAgJQAAgJACgIQADgJAHgFQAGgFALAAQAJAAAGAFQAGAFACAJIAQAAQgBgMgGgH").p("ACOApIAAATIAPAAIAAgTIgPAA").p("AAfioIgPAAIAAATIAPAAIAAgT").p("AgGipQgMAAgHAGQgHAFAAAMIAAAOIgQAAIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGAEgDQADgCAGAAQABAAADABQABAAACABIAAgOQgCAAgCgBQgCAAgDAA").p("AgyApIAAATIAPAAIAAgTIgPAA").p("ABbAxIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAFQACAEAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgNIgTAAIAAgcIgPAA").p("AAQgnIAPAAIAAhdIgPAAIAABd").p("AAsBdQAGAFABAJIAQAAQgBgMgFgHQgGgHgJgDQgIgEgLAAQgPABgJAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGANAAQASAAALgJQAKgKADgRIgQAAQgBAKgHAHQgGAFgMAAQgKAAgFgFQgGgEgDgIQgCgIAAgJQAAgJABgIQAEgJAGgFQAGgFALAAQAKAAAGAF").p("AgyBNIAABdIAPAAIAAhdIgPAA").p("AD2BRQgKgGgPgBQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgH").p("AD2BoQAEAIAAALQAAAMgEAIQgDAHgHAEQgHAEgIAAQgIAAgGgEQgHgEgEgHQgDgIgBgMQABgLADgIQAEgIAHgDQAGgFAIAAQAIAAAHAFQAHADADAI").p("ACOBNIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(48.9,68.4);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AgihZIglCzIAVAAIAMg4IAAAAQACADAGADQAHADAIAAQAMAAALgGQALgFAJgLIAAAAIgEATIAVAAIAbiBIgVAAIgPBIQgCALgHAJQgHAJgJAGQgKAGgLABQgJAAgHgFQgGgEAAgJQAAgDAAgEQABgCAAgFQABgDABgCIAQhNIgVAA").f();
	this.shape_1.setTransform(11.3,26.9);

	// Layer 1
	this.shape_2 = new Shape();
	this.shape_2.graphics.lf(["#d3dade","#e8ecec","#f0f4f4"],[0,0.702,1],6,32.3,6,-30.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_2.setTransform(57.7,48.8);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.coef_3;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.mass_3 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AA7gcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAEAEQAEADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgGgCQgFgCgDgEQgEgEAAgHIgQAAQAAAMAGAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgIgDQgHgCgIgCQgHgCgGgBQgIgCgEgDQgFgCAAgFQAAgFADgCQAEgDAEgCQAEAAAFAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgJAAgHAD").p("AgOgfQgKAAgJADQgJADgFAHQgGAHAAALIAPAAQABgJAGgEQAGgEAKAAQAFAAAFABQAFABACADQADAEAAAGQAAAFgEACQgEADgHABQgHABgIABQgIACgHACQgIADgEAGQgFAFAAALQAAAJAEAGQAFAFAHADQAGACAJAAQAKAAAIgDQAIgDAGgHQAAAHADAEQAEACAGAAQAEAAACAAQADAAACgCIAAgLQgCAAAAAAQgCAAgBAAQgEAAAAgCQgBgDAAgFIAAgvQAAgLgFgGQgFgFgIgCQgHgCgJAA").p("AgfAZQAEgCAFgBQAIgBAIgBQAGgBAFgDIAAAPQAAAFgDAFQgCAEgGAEQgHADgKAAQgEAAgEgBQgEgBgDgDQgCgDgBgFQABgGACgDQADgEAEgB").p("AhlhAIgpBrIgohrIgYAAIAACAIAQAAIAAhqIABAAIAoBqIAOAAIAphqIAABqIAQAAIAAiAIgXAA").p("ACVgcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAFAEQADADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgFgCQgGgCgDgEQgEgEAAgHIgQAAQABAMAFAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgHgDQgIgCgHgCQgIgCgGgBQgIgCgEgDQgEgCgBgFQABgFACgCQAEgDAEgCQAFAAAEAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgIAAgIAD").f();
	this.shape.setTransform(27.6,58.1);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("ABBhBQgNAAgMAHQgMAGgIAKQgDgMgJgGQgIgFgMAAQgNAAgMAHQgLAFgJALIAAgBIAFgTIgUAAIgbCAIAVAAIAOhCQACgKADgHQACgGAHgHQAGgGAIgFQAJgFAJAAQAIAAAFAEQAFAFAAAIQAAACgBAHQgBAGgCAIIgQBIIAUAAIAPhCQACgIACgHQADgIAFgFQAFgHAKgFQAIgGAKAAQAIAAAGAFQAFAFAAAIQAAADAAADQgBAEgBADIgSBRIAVAAIARhMQABgGABgHQABgHAAgGQAAgLgFgGQgFgGgIgDQgIgDgJAA").f();
	this.shape_1.setTransform(15.4,24.3);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#1494b8").p("AHRi3IArAAIhLh4IhLB4IAtAAIAAFKIA+AAIAAlK").f();
	this.shape_2.setTransform(56.2,34.2);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#b8d8f5","#71c4fc"],[0,1],-642,-47.5,-642.3,45.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.mass_3;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.formulaBox_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 3
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("A2tlpMAtcAAAQBQAAAABQIAAIzQAABPhQAAMgtcAAAQhQAAAAhPIAAozQAAhQBQAA").cp();
	this.shape.setTransform(150.2,33.2);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 4
	this.instance = new lib.Bitmap12();
	this.instance.setTransform(-1.9,-1.9);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.formulaBox_2;
p.nominalBounds = new Rectangle(-1.9,-1.9,305,71);

(lib.summ_pannel2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#e5f4fd").p("AV+lOIlKAAI+fAAIoRAAQhkAAAABkIAAHVQAABkBkAAIIRAAIefAAIFKAAQBkAAAAhkIAAnVQAAhkhkAA").f().s("#ffffff").ss(4,1,1,3).p("AV+lOQBkAAAABkIAAHVQAABkhkAAIlKAAI+fAAIoRAAQhkAAAAhkIAAnVQAAhkBkAAIIRAAIefAAIFKAA").cp();

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.summ_pannel2;
p.nominalBounds = new Rectangle(-150.4,-33.4,301.1,67);

(lib.forceOfFriction3 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AgWiIQgPABgKAGQgKAHgEALQgFAMAAAOQAAANAFAMQAFAKAJAGQAKAGAPAAQARAAAKgKQAKgJADgRIgQAAQgBAKgGAGQgHAGgKAAQgKAAgGgFQgGgEgDgIQgDgIAAgIQAAgKADgIQADgJAGgFQAGgFALAAQAJAAAHAFQAFAFABAJIAQAAQgBgLgFgIQgGgHgIgDQgJgEgKAA").p("AhIiIQgNAAgIAGQgIAGgFAKIgBAAIAAgTIgOAAIAABdIAPAAIAAgqQAAgRAIgKQAHgKATAAIAAgR").p("Ai4iIQgPABgKAGQgKAGgFALQgFAMAAANQAAAOAFALQAFALAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgLQAFgLAAgOQAAgNgFgMQgFgLgKgGQgKgGgPgB").p("AifhEQgEAJgGAEQgHADgIAAQgIAAgHgDQgHgEgDgJQgEgHAAgMQAAgLAEgHQADgJAHgEQAHgEAIAAQAIAAAHAEQAGAEAEAJQADAHAAALQAAAMgDAH").p("AijAoIAAATIAPAAIAAgTIgPAA").p("AgWAwIAAAcIgQAAIAAAOIAQAAIAAA6QAAAJACAFQADAEAFACQAEABAIAAIALAAIAAgOIgHAAQgGAAgCgBQgDgBAAgGIAAg5IASAAIAAgOIgSAAIAAgcIgPAA").p("AjxipIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjxAoIhVAAIAACBIASAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AjhBMIAABdIAQAAIAAgpQgBgSAIgKQAIgKASAAIAAgRQgMAAgIAGQgJAGgFAKIgBAAIAAgTIgOAA").p("AhVBJQgPABgKAGQgKAHgEALQgFAMAAANQAAAPAFAKQAFALAJAGQAKAGAOAAQASAAAKgJQALgKACgRIgPAAQgCAKgGAHQgHAGgLAAQgKAAgGgFQgGgFgCgIQgDgHAAgKQAAgJACgIQADgIAHgFQAGgFALAAQAJAAAGAEQAGAFABAJIARAAQgCgLgFgHQgFgIgKgDQgIgEgKAA").p("AijBMIAABdIAPAAIAAhdIgPAA").p("AE9iqQgNAAgGAGQgHAFAAAMIAAAOIgQAAIAAAOIAQAAIAABPIAPAAIAAhPIASAAIAAgOIgSAAIAAgNQAAgGADgCQAEgDAFAAQACAAACABQADAAACABIAAgOQgDAAgCAAQgDgBgCAA").p("ADdiIQgOABgKAGQgKAGgGALQgFAMAAANQAAAOAFALQAGALAKAHQAKAGAOAAQAPAAAKgGQAKgHAFgLQAGgLAAgOQAAgNgGgMQgFgLgKgGQgKgGgPgB").p("AD2hpQAEAHAAALQAAAMgEAHQgDAJgHAEQgGADgJAAQgIAAgGgDQgHgEgEgJQgDgHgBgMQABgLADgHQAEgJAHgEQAGgEAIAAQAJAAAGAEQAHAEADAJ").p("AByhkQgCgJgFgIQgFgIgIgFQgIgFgNgBQgMABgKAGQgKAGgGALQgFALAAAOQAAAOAFALQAFAMAKAGQAKAGAOAAQAQAAALgIQAKgIADgPIgPAAQgCAJgGAEQgHAEgJAAQgKAAgHgDQgGgFgDgHQgDgHAAgIIBGAAQAAgIgCgK").p("AAyhtQADgFAGgEQAGgEAIAAQAHAAAGAEQAGAEADAFQAEAGAAAIIg1AAQAAgIAEgG").p("AAdAoIAAATIAPAAIAAgTIgPAA").p("ACrBMIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgDAJAAQAJAAAFAFQAFAFAAAIIAAA/IAPAAIAAg9QAAgKgDgIQgCgHgHgFQgIgEgMgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAA").p("ACFBQQgKgGgPgBQgPABgKAGQgKAHgFALQgFAKAAAPQAAAOAFALQAFAKAKAHQAKAGAPAAQAPAAAKgGQAKgHAFgKQAFgLAAgOQAAgPgFgKQgFgLgKgH").p("ACFBnQAEAIAAAMQAAALgEAIQgEAIgGADQgHAFgIAAQgIAAgHgFQgGgDgEgIQgEgIAAgLQAAgMAEgIQAEgIAGgDQAHgEAIAAQAIAAAHAEQAGADAEAI").p("AAdBMIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(39.6,68.5);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AA+hYIh1AAIglCyIAYAAIARhSIBRAAIAFgUIhSAAIAMg4IBcAAIAFgU").p("ABDATQgBAEgBAFIgKAAIgCAJIALAAIgMA1IAKAAIAMg1IALAAIACgJIgMAAQABgEABgEQABgDACgDQACgCAFAAQACAAABAAQABAAABABIACgJQgCAAgCgBQgDAAgCAAQgGAAgEACQgDACgCAEQgBADgCAF").f();
	this.shape_1.setTransform(15.7,22);

	// Layer 1
	this.shape_2 = new Shape();
	this.shape_2.graphics.lf(["#d3dade","#e8ecec","#f0f4f4"],[0,0.702,1],6,32.3,6,-30.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_2.setTransform(57.7,48.8);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.forceOfFriction3;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.coef_4 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AGsiEIgTAAIAAgcIgPAAIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAEQACAFAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgN").p("AFNiHQgKAAgIAFQgIAEgEAIIgBAAIAAgOIgOAAIAABdIAPAAIAAg1QAAgIADgHQADgGAGgEQAGgEAKAAQAIAAAFAFQAFAFAAAJIAAA/IAPAAIAAg+QAAgKgCgHQgDgIgHgEQgIgEgLgB").p("AFVBdQAFAFABAJIAAA/IAPAAIAAg+QAAgKgDgHQgDgIgHgEQgHgEgNgBQgKAAgHAFQgIAEgFAIIAAAAIAAgOIgPAAIAABdIAQAAIAAg0QAAgJADgGQADgHAGgEQAGgEAKAAQAJAAAEAF").p("AhliEIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACABQACAAADABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgQAA").p("AisiAQgKAGgFALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAPAAALgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgGgEQgHgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgMgBQgNABgKAG").p("AiJh1QAGADADAGQAEAGABAHIg2AAQAAgHAEgGQAEgGAFgDQAGgEAIAAQAHAAAGAE").p("AkUiAQgKAGgGALQgFALAAAOQAAAOAFALQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgLAAgOQAAgOgGgLQgFgLgKgGQgKgGgPgBQgOABgKAG").p("Ajth1QAHAEADAIQAFAIAAALQAAAMgFAHQgDAIgHAEQgGAEgJAAQgIAAgGgEQgHgEgEgIQgDgHgBgMQABgLADgIQAEgIAHgEQAGgEAIAAQAJAAAGAE").p("AkZA2QADAAACABIAAgOQgDAAgCgBQgDAAgCAAQgNAAgGAGQgHAFAAAMIAAAOIgPAAIAAANIAPAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGADgDQAEgCAFAAQACAAACAB").p("AiAApIhUAAIAACBIARAAIAAg7IA7AAIAAgPIg7AAIAAgoIBDAAIAAgP").p("AlBiYQgIgJgLgFQgLgFgOAAQgTAAgOAJQgOAJgGAQQgIAPAAATQAAATAHAPQAHAPANAJQANAJAUAAQAYAAAPgOQAOgNADgZIgRAAQgBALgEAIQgFAJgIAEQgIAFgMAAQgPAAgKgHQgJgHgFgMQgEgNAAgOQAAgOAEgMQAFgMAJgHQAKgHAPAAQAJAAAIADQAHADAFAGQAFAGACAJIARAAQgCgOgHgJ").p("Al+BKQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgHQgKgGgPgB").p("AllBoQAFAIAAALQAAAMgFAIQgDAHgHAEQgGAEgJAAQgIAAgGgEQgGgEgFgHQgDgIgBgMQABgLADgIQAFgIAGgDQAGgFAIAAQAJAAAGAFQAHADADAI").p("AhwCqIAQAAIAAgqQgBgSAJgJQAHgKASAAIAAgRQgMAAgIAGQgJAFgFALIAAAAIAAgTIgPAAIAABd").p("ADliHQgMABgKAGQgJAGgGALQgGALAAAOQABAOAFALQAFALAJAHQAKAGAPAAQAQAAAKgIQAKgIAEgQIgPAAQgDAJgGAFQgGAEgKAAQgKAAgHgEQgGgEgDgHQgDgHAAgIIBGAAQAAgJgCgJQgBgJgFgIQgFgIgIgFQgJgFgNgB").p("AEAhfIg2AAQABgHADgGQADgGAGgDQAGgEAIAAQAIAAAGAEQAFADAEAGQADAGABAH").p("ACYiEIAABdIAPAAIAAhdIgPAA").p("ACYioIAAATIAPAAIAAgTIgPAA").p("AB/h5QgGgHgIgDQgJgEgKAAQgPABgKAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGAOAAQASAAAKgKQALgJACgRIgPAAQgCAKgGAGQgHAGgLAAQgKAAgGgFQgGgEgCgIQgDgIAAgJQAAgJACgIQADgJAHgFQAGgFALAAQAJAAAGAFQAGAFACAJIAQAAQgBgMgGgH").p("ACOApIAAATIAPAAIAAgTIgPAA").p("AAfioIgPAAIAAATIAPAAIAAgT").p("AgGipQgMAAgHAGQgHAFAAAMIAAAOIgQAAIAAANIAQAAIAABQIAPAAIAAhQIASAAIAAgNIgSAAIAAgNQAAgGAEgDQADgCAGAAQABAAADABQABAAACABIAAgOQgCAAgCgBQgCAAgDAA").p("AgyApIAAATIAPAAIAAgTIgPAA").p("ABbAxIAAAcIgQAAIAAANIAQAAIAAA7QAAAJACAFQACAEAFABQAFACAIAAIAMAAIAAgOIgHAAQgHAAgDgBQgCgCAAgFIAAg6IATAAIAAgNIgTAAIAAgcIgPAA").p("AAQgnIAPAAIAAhdIgPAAIAABd").p("AAsBdQAGAFABAJIAQAAQgBgMgFgHQgGgHgJgDQgIgEgLAAQgPABgJAGQgKAHgEALQgFALAAAOQAAAOAFALQAFALAJAGQAKAGANAAQASAAALgJQAKgKADgRIgQAAQgBAKgHAHQgGAFgMAAQgKAAgFgFQgGgEgDgIQgCgIAAgJQAAgJABgIQAEgJAGgFQAGgFALAAQAKAAAGAF").p("AgyBNIAABdIAPAAIAAhdIgPAA").p("AD2BRQgKgGgPgBQgOABgKAGQgKAHgGAKQgFALAAAOQAAAPAFAKQAGALAKAGQAKAHAOAAQAPAAAKgHQAKgGAFgLQAGgKAAgPQAAgOgGgLQgFgKgKgH").p("AD2BoQAEAIAAALQAAAMgEAIQgDAHgHAEQgHAEgIAAQgIAAgGgEQgHgEgEgHQgDgIgBgMQABgLADgIQAEgIAHgDQAGgFAIAAQAIAAAHAFQAHADADAI").p("ACOBNIAABdIAPAAIAAhdIgPAA").f();
	this.shape.setTransform(48.9,68.4);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("AgihZIglCzIAVAAIAMg4IAAAAQACADAGADQAHADAIAAQAMAAALgGQALgFAJgLIAAAAIgEATIAVAAIAbiBIgVAAIgPBIQgCALgHAJQgHAJgJAGQgKAGgLABQgJAAgHgFQgGgEAAgJQAAgDAAgEQABgCAAgFQABgDABgCIAQhNIgVAA").f();
	this.shape_1.setTransform(11.3,26.9);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#e80000").p("AGdmRIAAFLIgtAAIBLB3IBLh3IgsAAIAAlLIg9AA").f();
	this.shape_2.setTransform(55.8,45.5);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#ffaaa6","#e56b64"],[0,1],50.4,-48.2,50.4,48.3).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.coef_4;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.mass_4 = function() {
	this.initialize();

	// Layer 2
	this.shape = new Shape();
	this.shape.graphics.f("#000000").p("AA7gcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAEAEQAEADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgGgCQgFgCgDgEQgEgEAAgHIgQAAQAAAMAGAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgIgDQgHgCgIgCQgHgCgGgBQgIgCgEgDQgFgCAAgFQAAgFADgCQAEgDAEgCQAEAAAFAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgJAAgHAD").p("AgOgfQgKAAgJADQgJADgFAHQgGAHAAALIAPAAQABgJAGgEQAGgEAKAAQAFAAAFABQAFABACADQADAEAAAGQAAAFgEACQgEADgHABQgHABgIABQgIACgHACQgIADgEAGQgFAFAAALQAAAJAEAGQAFAFAHADQAGACAJAAQAKAAAIgDQAIgDAGgHQAAAHADAEQAEACAGAAQAEAAACAAQADAAACgCIAAgLQgCAAAAAAQgCAAgBAAQgEAAAAgCQgBgDAAgFIAAgvQAAgLgFgGQgFgFgIgCQgHgCgJAA").p("AgfAZQAEgCAFgBQAIgBAIgBQAGgBAFgDIAAAPQAAAFgDAFQgCAEgGAEQgHADgKAAQgEAAgEgBQgEgBgDgDQgCgDgBgFQABgGACgDQADgEAEgB").p("AhlhAIgpBrIgohrIgYAAIAACAIAQAAIAAhqIABAAIAoBqIAOAAIAphqIAABqIAQAAIAAiAIgXAA").p("ACVgcQgJADgFAGQgFAGAAAJQAAAIAEAFQAFAFAHADQAHADAHABQAJACAGACQAHABAFAEQADADABAGQgBAFgDADQgDADgFABQgFACgFgBQgHABgFgCQgGgCgDgEQgEgEAAgHIgQAAQABAMAFAHQAFAHAKADQAIACALAAQAJABAJgDQAJgDAGgGQAGgGAAgLQAAgJgEgGQgEgFgHgDQgIgCgHgCQgIgCgGgBQgIgCgEgDQgEgCgBgFQABgFACgCQAEgDAEgCQAFAAAEAAQAFAAAFABQAEACAEADQADAEABAFIAPAAQgBgLgFgGQgFgGgIgDQgJgDgKAAQgIAAgIAD").f();
	this.shape.setTransform(27.6,58.1);

	this.shape_1 = new Shape();
	this.shape_1.graphics.f("#000000").p("ABBhBQgNAAgMAHQgMAGgIAKQgDgMgJgGQgIgFgMAAQgNAAgMAHQgLAFgJALIAAgBIAFgTIgUAAIgbCAIAVAAIAOhCQACgKADgHQACgGAHgHQAGgGAIgFQAJgFAJAAQAIAAAFAEQAFAFAAAIQAAACgBAHQgBAGgCAIIgQBIIAUAAIAPhCQACgIACgHQADgIAFgFQAFgHAKgFQAIgGAKAAQAIAAAGAFQAFAFAAAIQAAADAAADQgBAEgBADIgSBRIAVAAIARhMQABgGABgHQABgHAAgGQAAgLgFgGQgFgGgIgDQgIgDgJAA").f();
	this.shape_1.setTransform(15.4,24.3);

	this.shape_2 = new Shape();
	this.shape_2.graphics.f("#1494b8").p("AHRi3IArAAIhLh4IhLB4IAtAAIAAFKIA+AAIAAlK").f();
	this.shape_2.setTransform(56.2,34.2);

	// Layer 1
	this.shape_3 = new Shape();
	this.shape_3.graphics.lf(["#b8d8f5","#71c4fc"],[0,1],-642,-47.5,-642.3,45.2).p("AHdnnIu5AAQhkAAAABkIAAMHQAABkBkAAIO5AAQBkAAAAhkIAAsHQAAhkhkAA").f();
	this.shape_3.setTransform(57.7,48.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new Container();
p.constructor = lib.mass_4;
p.nominalBounds = new Rectangle(0,0,115.4,97.6);

(lib.formulaBox_31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);


	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(Tween.get(this).wait(0).call(this.frame_0).wait(2));

	// Layer 3
	this.shape = new Shape();
	this.shape.graphics.f().s("#ffcc00").ss(4,0,0,3).p("A2tlpMAtcAAAQBQAAAABQIAAIzQAABPhQAAMgtcAAAQhQAAAAhPIAAozQAAhQBQAA").cp();
	this.shape.setTransform(150.2,33.2);

	this.timeline.addTween(Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).wait(1));

	// Layer 4
	this.instance = new lib.Bitmap11();
	this.instance.setTransform(-1.9,-1.9);

	this.timeline.addTween(Tween.get({}).to({state:[{t:this.instance}]}).wait(2));

}).prototype = p = new MovieClip();

p.constructor = lib.formulaBox_31;
p.nominalBounds = new Rectangle(-1.9,-1.9,305,71);

(lib.summ_pannel3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new Shape();
	this.shape.graphics.f("#e5f4fd").p("AV+lOIlKAAI+fAAIoRAAQhkAAAABkIAAHVQAABkBkAAIIRAAIefAAIFKAAQBkAAAAhkIAAnVQAAhkhkAA").f().s("#ffffff").ss(4,1,1,3).p("AV+lOQBkAAAABkIAAHVQAABkhkAAIlKAAI+fAAIoRAAQhkAAAAhkIAAnVQAAhkBkAAIIRAAIefAAIFKAA").cp();

	this.addChild(this.shape);
}).prototype = p = new Container();
p.constructor = lib.summ_pannel3;
p.nominalBounds = new Rectangle(-150.4,-33.4,301.1,67);

(lib.Bitmap1 = function() {
	this.initialize(images.Bitmap1);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap1;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap10 = function() {
	this.initialize(images.Bitmap10);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap10;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap11 = function() {
	this.initialize(images.Bitmap11);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap11;
p.nominalBounds = new Rectangle(0,0,305,71);

(lib.Bitmap12 = function() {
	this.initialize(images.Bitmap12);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap12;
p.nominalBounds = new Rectangle(0,0,305,71);

(lib.Bitmap13 = function() {
	this.initialize(images.Bitmap13);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap13;
p.nominalBounds = new Rectangle(0,0,305,71);

(lib.Bitmap2 = function() {
	this.initialize(images.Bitmap2);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap2;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap3 = function() {
	this.initialize(images.Bitmap3);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap3;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap4 = function() {
	this.initialize(images.Bitmap4);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap4;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap5 = function() {
	this.initialize(images.Bitmap5);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap5;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap6 = function() {
	this.initialize(images.Bitmap6);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap6;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap7 = function() {
	this.initialize(images.Bitmap7);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap7;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap8 = function() {
	this.initialize(images.Bitmap8);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap8;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.Bitmap9 = function() {
	this.initialize(images.Bitmap9);
}).prototype = new Bitmap();
p.constructor = lib.Bitmap9;
p.nominalBounds = new Rectangle(0,0,115,98);

(lib.mcStartScreen = function() {
	this.initialize();

	// Layer 1
	this.mcPlay = new lib.play();
	this.mcPlay.setTransform(512,245.5,1,1,0,0,0,47,47);

	this.shape = new Shape();
	this.shape.graphics.f("rgba(0,0,0,0.337)").p("EBQAgmWMif/AAAMAAABMtMCf/AAAMAAAhMt").f();
	this.shape.setTransform(512,245.5);
	this.shape.scaleY =1.02
	this.addChild(this.shape,this.mcPlay);
}).prototype = p = new Container();
p.constructor = lib.mcStartScreen;
p.nominalBounds = new Rectangle(0,0,1024,491);

(lib.play = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.play_1();

	this.addChild(this.instance);
}).prototype = p = new Container();
p.constructor = lib.play;
p.nominalBounds = new Rectangle(0,0,94,94);

(lib.play_1 = function() {
	this.initialize(images.play_1);
}).prototype = new Bitmap();
p.constructor = lib.play_1;
p.nominalBounds = new Rectangle(0,0,94,94);

minalBounds = new Rectangle(0,0,720,80);


// symbols:
(lib.closeCaptioning = function() {
	this.initialize();

	// Layer 1
	this.tf = new Text("This x2is one line\nand anotherrrrrh22kkkλ°", "16px undefined", "#000000");
	this.tf.textBaseline = "top";
	this.tf.lineHeight = 18;
	this.tf.lineWidth = 688;
	this.tf.setTransform(11,9.2);

	this.instance = new lib.CloseCaption();

	this.addChild(this.instance,this.tf);
}).prototype = p = new Container();
p.constructor = lib.closeCaptioning;
p.nominalBounds = new Rectangle(0,0,720,80);

(lib.CloseCaption = function() {
	this.initialize(images.CloseCaption);
}).prototype = new Bitmap();
p.constructor = lib.CloseCaption;
p.nominalBounds = new Rectangle(0,0,720,80);